// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"context"
)

type Querier interface {
	ShopFetch(ctx context.Context) ([]Shop, error)
	ShopFindById(ctx context.Context, id string) (Shop, error)
	ShopFindByIds(ctx context.Context, ids []string) ([]Shop, error)
	UpsertShop(ctx context.Context, arg UpsertShopParams) error
}

var _ Querier = (*Queries)(nil)
