version: "3"
volumes:
  db-store:
    driver: local

services:
  db:
    image: mysql:8.0.38-bookworm
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hackathon
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      LANG: C.UTF-8
    command: --collation-server=utf8mb4_general_ci
    platform: linux/x86_64
  app:
    image: go:1.17.2
    volumes:
      - .:/app
    working_dir: /app
    tty: true